### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by nissy7ok** [nissy7ok/chat-space#11]
# IPアドレス
54.168.196.130

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。

**Comment by nissy7ok** [comment]
ありがとうございます！
